version: 2.1

jobs:
  setup:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run: npm install
  build:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run: npm run build
  test-frontend:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run: npm run test
  test-server:
    docker:
      - image: node:current-alpine
    steps:
      - checkout
      - run: npm run test-server

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test-frontend:
          requires:
            - setup
      - test-server:
          requires:
            - setup


